export default function Reports() {
  return (
    <div className="p-8">
      <h1 className="text-2xl font-bold mb-4">Reports</h1>
      <p className="text-gray-600 mb-6">
        Below is a list of reports generated from the system. You can view or download detailed
        reports for each module.
      </p>

      {/* Reports Table */}
      <div className="overflow-x-auto">
        <table className="min-w-full table-auto border-collapse">
          <thead>
            <tr>
              <th className="px-4 py-2 border-b text-center">Report Name</th>
              <th className="px-4 py-2 border-b text-center">Generated By</th>
              <th className="px-4 py-2 border-b text-center">Date</th>
              <th className="px-4 py-2 border-b text-center">Actions</th>
            </tr>
          </thead>
          <tbody>
            {/* Patient Registration Report */}
            <tr className="hover:bg-gray-100">
              <td className="px-4 py-2 border-b text-center">Patient Registration Report</td>
              <td className="px-4 py-2 border-b text-center">Receptionist</td>
              <td className="px-4 py-2 border-b text-center">2024-11-23</td>
              <td className="px-4 py-2 border-b text-center">
                <button className="bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-600">
                  View
                </button>
                <button className="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600 ml-2">
                  Download
                </button>
              </td>
            </tr>
            {/* Clinical Notes Report */}
            <tr className="hover:bg-gray-100">
              <td className="px-4 py-2 border-b text-center">Clinical Notes Report</td>
              <td className="px-4 py-2 border-b text-center">Clinical Officer</td>
              <td className="px-4 py-2 border-b text-center">2024-11-22</td>
              <td className="px-4 py-2 border-b text-center">
                <button className="bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-600">
                  View
                </button>
                <button className="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600 ml-2">
                  Download
                </button>
              </td>
            </tr>
            {/* Vaccination Report */}
            <tr className="hover:bg-gray-100">
              <td className="px-4 py-2 border-b text-center">Vaccination Report</td>
              <td className="px-4 py-2 border-b text-center">Nurse</td>
              <td className="px-4 py-2 border-b text-center">2024-11-21</td>
              <td className="px-4 py-2 border-b text-center">
                <button className="bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-600">
                  View
                </button>
                <button className="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600 ml-2">
                  Download
                </button>
              </td>
            </tr>
            {/* Inventory Report */}
            <tr className="hover:bg-gray-100">
              <td className="px-4 py-2 border-b text-center">Inventory Report</td>
              <td className="px-4 py-2 border-b text-center">Admin</td>
              <td className="px-4 py-2 border-b text-center">2024-11-20</td>
              <td className="px-4 py-2 border-b text-center">
                <button className="bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-600">
                  View
                </button>
                <button className="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600 ml-2">
                  Download
                </button>
              </td>
            </tr>
            {/* Billing Report */}
            <tr className="hover:bg-gray-100">
              <td className="px-4 py-2 border-b text-center">Billing Report</td>
              <td className="px-4 py-2 border-b text-center">Manager</td>
              <td className="px-4 py-2 border-b text-center">2024-11-19</td>
              <td className="px-4 py-2 border-b text-center">
                <button className="bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-600">
                  View
                </button>
                <button className="bg-green-500 text-white px-3 py-1 rounded hover:bg-green-600 ml-2">
                  Download
                </button>
              </td>
            </tr>
            {/* Add more reports as needed */}
          </tbody>
        </table>
      </div>
    </div>
  );
}
